name: ci2
on: push
jobs:
  CI:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: false
    strategy:
      max-parallel: 3
      matrix:
        test: [test-1, test-2, test-3]
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
