name: ci2
on: push
jobs:
  CI:
    runs-on: self-hosted
    strategy:
      matrix:
        test: [test-1, test-2, test-3]
        max-parallel: 2
      parallel: true  
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
