name: ci2
on: push
 
jobs:
  CI:
    name: CI Tests
    runs-on: self-hosted
    strategy:
      matrix:
        max-parallel: 2
        test: [test-1, test-2]
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
