name: ci2
on: workflow_dispatch
jobs:
  CI:
    runs-on: self-hosted
    strategy:
      matrix:
        test: [test-1, test-2]
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
