name: ci2
on: push
jobs:
  CI:
    runs-on: self-hosted
    strategy:
      matrix:
        test: [test-1, test-2, test-3]
      max-parallel: 3 # Execute até 3 jobs simultaneamente
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
