name: ci2
on: push
jobs:
  CI:
    runs-on: self-hosted
    strategy:
      matrix:
        test: [test-1, test-2, test-3, test-4]
    steps:
      - name: sleep
        run: sleep 300
        shell: bash
